--------------------------------------------------------
--  File created - Friday-May-24-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TRN_PATIENTS
--------------------------------------------------------

  CREATE TABLE "HR"."TRN_PATIENTS" 
   (	"PAT_ID" NUMBER(20,0), 
	"PAT_NAME" VARCHAR2(50 BYTE), 
	"PAT_AGE" NUMBER(3,0), 
	"CONTACT_NUM" NUMBER(10,0), 
	"USER_NAME" VARCHAR2(50 BYTE), 
	"USER_PWD" VARCHAR2(20 BYTE), 
	"PAT_GENDER" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HR.TRN_PATIENTS
SET DEFINE OFF;
Insert into HR.TRN_PATIENTS (PAT_ID,PAT_NAME,PAT_AGE,CONTACT_NUM,USER_NAME,USER_PWD,PAT_GENDER) values (47,'afrin',23,8651209872,'afrin','gh','female');
Insert into HR.TRN_PATIENTS (PAT_ID,PAT_NAME,PAT_AGE,CONTACT_NUM,USER_NAME,USER_PWD,PAT_GENDER) values (15,'pavi',21,7339683929,'pavi','1234','female');
Insert into HR.TRN_PATIENTS (PAT_ID,PAT_NAME,PAT_AGE,CONTACT_NUM,USER_NAME,USER_PWD,PAT_GENDER) values (48,'daniel',32,8769543210,'daniel','890','male');
Insert into HR.TRN_PATIENTS (PAT_ID,PAT_NAME,PAT_AGE,CONTACT_NUM,USER_NAME,USER_PWD,PAT_GENDER) values (22,'aruna',23,7890123456,'aruna','12345','female');
Insert into HR.TRN_PATIENTS (PAT_ID,PAT_NAME,PAT_AGE,CONTACT_NUM,USER_NAME,USER_PWD,PAT_GENDER) values (43,'karthi',21,8970965432,'karthi','345','male');
Insert into HR.TRN_PATIENTS (PAT_ID,PAT_NAME,PAT_AGE,CONTACT_NUM,USER_NAME,USER_PWD,PAT_GENDER) values (49,'naveen',67,9000675421,'navi','128','male');
Insert into HR.TRN_PATIENTS (PAT_ID,PAT_NAME,PAT_AGE,CONTACT_NUM,USER_NAME,USER_PWD,PAT_GENDER) values (19,'saranya',21,9003209327,'saran','456','female');
Insert into HR.TRN_PATIENTS (PAT_ID,PAT_NAME,PAT_AGE,CONTACT_NUM,USER_NAME,USER_PWD,PAT_GENDER) values (20,'yuvalakshman',21,7598221707,'yuva','Donyuvi77**','male');
Insert into HR.TRN_PATIENTS (PAT_ID,PAT_NAME,PAT_AGE,CONTACT_NUM,USER_NAME,USER_PWD,PAT_GENDER) values (51,'anbagam',21,9867590021,'anbu','orange','male');
--------------------------------------------------------
--  DDL for Index TRN_PAT_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."TRN_PAT_ID" ON "HR"."TRN_PATIENTS" ("PAT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CONTACT_NUM
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."CONTACT_NUM" ON "HR"."TRN_PATIENTS" ("CONTACT_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table TRN_PATIENTS
--------------------------------------------------------

  ALTER TABLE "HR"."TRN_PATIENTS" ADD CONSTRAINT "CONTACT_NUM" UNIQUE ("CONTACT_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "HR"."TRN_PATIENTS" MODIFY ("PAT_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TRN_PATIENTS" MODIFY ("PAT_AGE" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TRN_PATIENTS" MODIFY ("CONTACT_NUM" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TRN_PATIENTS" MODIFY ("USER_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TRN_PATIENTS" MODIFY ("PAT_GENDER" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TRN_PATIENTS" ADD CONSTRAINT "TRN_PAT_ID" PRIMARY KEY ("PAT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "HR"."TRN_PATIENTS" MODIFY ("USER_PWD" CONSTRAINT "USER_PWD" NOT NULL ENABLE);
