--------------------------------------------------------
--  File created - Friday-May-24-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TRN_APPOINTMENT
--------------------------------------------------------

  CREATE TABLE "HR"."TRN_APPOINTMENT" 
   (	"APP_ID" NUMBER(20,0), 
	"DOC_NAME" VARCHAR2(50 BYTE), 
	"APP_TIME" VARCHAR2(60 BYTE), 
	"APP_DATE" DATE, 
	"USERID" VARCHAR2(30 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HR.TRN_APPOINTMENT
SET DEFINE OFF;
Insert into HR.TRN_APPOINTMENT (APP_ID,DOC_NAME,APP_TIME,APP_DATE,USERID) values (118,'Adam','10am to 12pm',to_date('30-05-19','DD-MM-RR'),'pavi');
Insert into HR.TRN_APPOINTMENT (APP_ID,DOC_NAME,APP_TIME,APP_DATE,USERID) values (135,'Roofus','8am to 9am',to_date('25-05-19','DD-MM-RR'),'saran');
--------------------------------------------------------
--  DDL for Index SYS_C004291
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C004291" ON "HR"."TRN_APPOINTMENT" ("APP_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table TRN_APPOINTMENT
--------------------------------------------------------

  ALTER TABLE "HR"."TRN_APPOINTMENT" MODIFY ("DOC_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TRN_APPOINTMENT" MODIFY ("APP_TIME" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TRN_APPOINTMENT" ADD PRIMARY KEY ("APP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
